routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Route::group(['middleware' => ['auth','cekrole:petugas']], function(){
Route::resource('kategori','KategoriController')->except(['delete']);
Route::get('kategori/delete/{kategori}', 'KategoriController@destroy')->name('kategori.delete');
Route::resource('penerbit','PenerbitController')->except(['delete']);
Route::get('penerbit/delete/{penerbit}', 'PenerbitController@destroy')->name('penerbit.delete');
Route::resource('buku','BukuController')->except(['delete']);
Route::get('buku/delete/{buku}', 'BukuController@destroy')->name('buku.delete');
Route::resource('dashadmin','DashAdminController');
Route::resource('member','MemberController');
// });

// Route::group(['middleware' => ['auth','cekrole:member']], function(){
Route::get('/home', 'UserDashboardController@index')->name('home');
#dashboard route
Route::get('/dashboard', 'UserDashboardController@index')->name('dashboard.index');
Route::get('/dashboard/{id}/show', 'UserDashboardController@show');
Route::put('/dashboard/{id}/komen', 'KomentarBukuController@update');
Route::get('/dashboard/cari', 'UserDashboardController@cari');
Route::post('/dashboard/{id}/download', 'UserDashboardController@downloadfile');

#profile route
Route::get('/profil', 'ProfilController@index')->name('profil.index');
Route::put('/profil/{id}', 'ProfilController@update');
Route::put('/profil/{id}/updatefoto', 'ProfilController@updatefoto');

#koleksi route
Route::resource('/koleksi','KoleksiController')->except(['store']);
Route::post('/koleksi/{id}/add', 'KoleksiController@store')->name('add.book');
Route::post('/koleksi/{id}/view', 'KoleksiController@show');

#histori route
Route::resource('/histori','HistoriController');

// });

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar header-navbar pcoded-header">
                <div class="navbar-wrapper">
                    <div class="navbar-logo">
                        <a class="mobile-menu waves-effect waves-light" id="mobile-collapse" href="#!">
                            <i class="ti-menu"></i>
                        </a>
                        <div class="mobile-search waves-effect waves-light">
                            <div class="header-search">
                                <div class="main-search morphsearch-search">
                                    <div class="input-group">
                                        <span class="input-group-prepend search-close"><i class="ti-close input-group-text"></i></span>
                                        <input type="text" class="form-control" placeholder="Enter Keyword">
                                        <span class="input-group-append search-btn"><i class="ti-search input-group-text"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="index.html" >
                            <img class="img-fluid ml-5" src="{{asset('assets/images/eclib-logo.png')}}" style="max-width : 130px; height: 35px" alt="Theme-Logo" />
                            
                        </a>
                        <a class="mobile-options waves-effect waves-light">
                            <i class="ti-more"></i>
                        </a>
                    </div>
                    <div class="navbar-container container-fluid">
                        <ul class="nav-left">
                            <li>
                                <div class="sidebar_toggle"><a href="javascript:void(0)"><i class="ti-menu"></i></a></div>
                            </li>
                            <li>
                                <a href="#" onclick="javascript:toggleFullScreen()" class="waves-effect waves-light">
                                    <i class="ti-fullscreen"></i>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav-right">
                            <li class="user-profile header-notification">
                                <a href="#!" class="waves-effect waves-light">
                                    <img src="{{asset('assets/images/profil.png')}}" class="img-radius" alt="User-Profile-Image">
                                    <span>{{Auth::user()->name}}</span>
                                    <i class="ti-angle-down"></i>
                                </a>
                                <ul class="show-notification profile-notification">
                                    <li class="waves-effect waves-light">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();"><i class="ti-layout-sidebar-left"></i> 
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

resources/views/layouts/partials/sidebar.blade.php
 <nav class="pcoded-navbar">
                        <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
                        <div class="pcoded-inner-navbar main-menu">
                            <div class="">
                                <div class="main-menu-header">
                                    <img class="img-80 img-radius" src="{{asset('assets/images/profil.png')}}" alt="User-Profile-Image">
                                    <div class="user-details">
                                        <span id="more-details">{{ Auth::user()->name}}</span>
                                    </div>
                                </div>
                                
                            </div>
                            
                            <div class="pcoded-navigation-label">Navigation</div>
                            <ul class="pcoded-item pcoded-left-item">
                                <li class="">
                                    <a href="{{ route("dashadmin.index") }}" class="waves-effect waves-dark">
                                        <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                                        <span class="pcoded-mtext">Dashboard</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                                    <hr>
                                <li class="">
                                    <a href="{{ route("member.index") }}" class="waves-effect waves-dark">
                                        <span class="pcoded-micon"><i class="ti-user"></i><b>D</b></span>
                                        <span class="pcoded-mtext">Member</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li><hr>
                                <li class="">
                                    <a href="{{ route("kategori.index") }}" class="waves-effect waves-dark">
                                        <span class="pcoded-micon"><i class="ti-vector"></i><b>D</b></span>
                                        <span class="pcoded-mtext">Kategori</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li><hr>
                                <li class="">
                                    <a href="{{ route("penerbit.index") }}" class="waves-effect waves-dark">
                                        <span class="pcoded-micon"><i class="ti-ruler-pencil"></i><b>D</b></span>
                                        <span class="pcoded-mtext">Penerbit</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li><hr>
                                <li class="">
                                    <a href="{{ route("buku.index") }}" class="waves-effect waves-dark">
                                        <span class="pcoded-micon"><i class="ti-book"></i><b>D</b></span>
                                        <span class="pcoded-mtext">Buku</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                            </ul>
                        
                                
                            </ul>
                           
                        </div>
                    </nav>